[app_servers]
app1 ansible_host=10.0.11.221
app2 ansible_host=10.0.11.103

[app_servers:vars]
ansible_user=ubuntu
# 깃허브 액션에서 파일로 생성할 pem 키 경로
ansible_ssh_private_key_file=./ktcloud-key.pem
# 처음 접속할 때 yes/no 묻는 거 생략
ansible_ssh_common_args='-o StrictHostKeyChecking=no'