[NAT]
natInstance ansible_host=3.36.16.81

[bastion]
monitoring ansible_host=3.39.69.234

[app_servers]
app1 ansible_host=10.0.11.101

[all:vars]
ansible_user=ubuntu
# 깃허브 액션에서 파일로 생성할 pem 키 경로
ansible_ssh_private_key_file=./ktcloud-key.pem
# 처음 접속할 때 yes/no 묻는 거 생략
ansible_host_key_checking=False

[app_servers:vars] 
# ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ./ktcloud-key.pem -o StrictHostKeyChecking=no -W %h:%p -q ubuntu@3.36.16.81" '