name: Deploy to Private EC2

on:
  push:
    branches:
      - feature/setup-github-runner

jobs:
  deploy:
    runs-on: self-hosted # <--- 이게 중요! Monitoring EC2에서 돌아가게 함
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH Key file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > ktcloud-key.pem
          chmod 400 ktcloud-key.pem

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts.ini deploy_app.yml
